### ISSUE TITLE
zluda.exe won't launch any program

### ISSUE THREAD

**Issue by Viniciuuz** [lshqqytiger/ZLUDA#1]
every time i try to launch any program using your version of zluda it won't launch, but the same program works fine with vosen's version. I didn't try building it from source, would that make any difference? 

tested on a rx 6600 on the latest driver version (31.0.24002.92, adrenalin 24.1.1). Windows 22h2 build 19045.4046.

a video demonstrating the issue can be viewed here: https://www.youtube.com/watch?v=iuSMtXo7FGo

**Comment by lshqqytiger** [comment]
Can't reproduce. Could you try again with latest release? (v3.5-win)
![스크린샷 2024-02-23 223301](https://github.com/lshqqytiger/ZLUDA/assets/39524005/d7488f73-d530-413e-aa76-5ea8c7759758)

**Comment by Viniciuuz** [comment]
working now with the latest release, thanks

![image](https://github.com/lshqqytiger/ZLUDA/assets/37600695/b7015917-6fe1-44a6-830a-ca24d181df97)

**Comment by Viniciuuz** [comment]
v3.5-win fixed my issue
