### ISSUE TITLE
Zluda 3.5 won't start program because Hiprtc0507.dll not found

### ISSUE THREAD

**Issue by gioxyer** [lshqqytiger/ZLUDA#3]
I just try to start Zluda 3.5, but it wouldn't start because Hiprtc0507.dll not found. The main error display "The code execution cannot continue because hiprtc0507.dll was not found. To solve the problem, try reinstalling the software". Hope can help.

![Screenshot (686)](https://github.com/lshqqytiger/ZLUDA/assets/161426313/b7cca924-a9c9-4f4d-9b23-503367b5e864)
![Screenshot (687)](https://github.com/lshqqytiger/ZLUDA/assets/161426313/db85c6f9-c22d-4816-9815-38942d7f3eea)
![Screenshot (688)](https://github.com/lshqqytiger/ZLUDA/assets/161426313/363c4bba-f0d8-4652-b24f-d02ab689f65e)
![Screenshot (689)](https://github.com/lshqqytiger/ZLUDA/assets/161426313/ab4b9286-b609-4dee-98ec-88b28aa98e1f)

**Comment by gioxyer** [comment]
I notice the main error, seems that module isn't inside the folder, I download from:
https://github.com/GPUOpen-LibrariesAndSDKs/Orochi/tree/f401a29869bc4eae64b0d10f3ae35e284cb42bf7/contrib/bin/win64

I download hiprtc0503.dll
![Screenshot (696)](https://github.com/lshqqytiger/ZLUDA/assets/161426313/750336c9-6a6e-41e3-85d5-1b515444964a)

Path to follow:
Download hiprtc0503.dll
Copy in zluda 3.5 folder
Rename from hiprtc0503.dll to hiprtc0507.dll (in my case, based from different driver and gpu) 

ZLUDA recognition
![Screenshot (697)](https://github.com/lshqqytiger/ZLUDA/assets/161426313/174a2ed5-132c-4833-be5f-895d8ad79429)

Working on viewport and render:
![Screenshot (702)](https://github.com/lshqqytiger/ZLUDA/assets/161426313/89544c62-c7a0-474e-aae9-429367b6e663)

**Comment by gioxyer** [comment]
Thanks for sharing, I tested with the other method different software 3D and non 3D seems working with also SDK, probably I should install officially on AMD, but seems pretty stable

**Comment by GentlemanMC** [comment]
i also had the same issue, copying these files (hiprtc0503.dll and hiprtc0507.dll) to zluda dir fixed it
