### ISSUE TITLE
Newer versions of Zluda don't work with KoboldCPP due to --cublas command being removed.

### ISSUE THREAD

**Issue by EmanuelOverride** [lshqqytiger/ZLUDA#43]
As title says. With 11cc, replacing cublas64_11.dll without injecting causes koboldcpp_cublas.dll to fail (file not found), while doing the same and injecting --cublas works fine. It's probably a hacky way of doing it in the first place, since I'm pretty sure Zluda would work as is if GPU check of native cublas64_11.dll was circumvented, but the hack works with all version of KoboldCPP, at least as far as Zluda 11cc.

**Comment by lshqqytiger** [comment]
The removal of --cublas argument was reverted in v3.8.4.

**Comment by EmanuelOverride** [comment]
Cool! Alright, tested it out. Replacing native cublas64_11.dll with the 3.8.4 cublas.dll, the application now fails with error:

```
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.dll
:0:C:\constructicon\builds\gfx\two\23.19\drivers\compute\clr\hipamd\src\hip_platform.cpp:123 : 18137902256 us: [pid:11312 tid:0x1f9c] Cannot register Static Global Var, error:13
```

Meanwhile, cublas.dll from 3.8.3 works fine with the restored argument in 3.8.4. So, just throwing the error out there, in case it means anything. This is with HIP 5.7, I'll try 6 at a later date.

**Comment by EmanuelOverride** [comment]
Cool. Works perfectly.
