### ISSUE TITLE
v3.8.3 has no cudart file

### ISSUE THREAD

**Issue by cyber827** [lshqqytiger/ZLUDA#44]
Trying to update the [comfyui ZLUDA fork ](https://github.com/patientx/ComfyUI-Zluda) which uses [v3.8-rocm5](https://github.com/lshqqytiger/ZLUDA/releases/tag/rel.11cc5844514f93161e0e74387f04e2c537705a82) to [v3.8.3](https://github.com/lshqqytiger/ZLUDA/releases/tag/rel.1c238a959f2aafdb9900f6801b61d9c0318040a2), but neither the [ZLUDA-windows-rocm5-amd64.zip](https://github.com/lshqqytiger/ZLUDA/releases/download/rel.1c238a959f2aafdb9900f6801b61d9c0318040a2/ZLUDA-windows-rocm5-amd64.zip) or [ZLUDA-windows-rocm6-amd64.zip](https://github.com/lshqqytiger/ZLUDA/releases/download/rel.1c238a959f2aafdb9900f6801b61d9c0318040a2/ZLUDA-windows-rocm6-amd64.zip) have the cudart.dll file that  [v3.8-rocm5](https://github.com/lshqqytiger/ZLUDA/releases/tag/rel.11cc5844514f93161e0e74387f04e2c537705a82) has. 

Updating the original v3.8 files with the v3.8.3 files from the .zip and keeping the cudart.dll file from the v3.8 results in comfyui creating blurry images. Tried with both HIP SDK 5.7 and HIP SDK 6.1 installed.

**Comment by lshqqytiger** [comment]
v3.8.4 was released with cudart.dll.
