### ISSUE TITLE
Release version V3.6, there is no zluda.exe file in ZLUDA-windows-amd64.zip

### ISSUE THREAD

**Issue by ws132** [lshqqytiger/ZLUDA#6]
Maybe I can continue to use the old version of exe?

**Comment by gioxyer** [comment]
I had the same problem, you should try [v3.7-pre2], seems works fine, even if it isn't official release yet (https://github.com/lshqqytiger/ZLUDA/releases/tag/rel.2812b1db443e73790acf89660d4f3a6bcf192eee)

**Comment by lshqqytiger** [comment]
You can use exe file of older releases. There's no changes for zluda.exe.

**Comment by ws132** [comment]
> You can use exe file of older releases. There's no changes for zluda.exe.

Thanks, I will close this question
